- core/tsnclient/get_all_streams.go
- core/types/tsn_client.go
- tests/integration/assets/assets.go
- tests/integration/assets/not_a_stream.kf
- tests/integration/get_all_streams_test.go
Implemented the `GetAllStreams` method to fetch all streams from the TSN network. Added integration tests to validate the functionality, ensuring only valid streams are listed.
Included tests that should pass
> feat: get all streams from network

- core/contracts/composed_stream_template.kf
resolves: https://github.com/truflation/tsn-sdk/issues/18
> chore: update composed stream template

- core/types/stream.go
resolves: https://github.com/truflation/tsn-sdk/issues/21
> feat: get stream type

- core/util/stream_id.go
resolves: https://github.com/truflation/tsn-sdk/issues/23
> fix: character missing from unmarshal streamId

- core/contractsapi/abstract_api.go
- core/types/composed_stream.go
resolve: https://github.com/truflation/tsn-sdk/issues/25
resolve: https://github.com/truflation/tsn-sdk/issues/26
> feat: custom marshal for taxonomyItem and fix wrong parameter

- core/contracts/composed_stream_template.kf
- core/contracts/primitive_stream.kf
- tests/integration/composed_stream_test.go
See https://github.com/truflation/tsn-data-provider/pull/222
> chore: optimize contract's query around return next 

- core/contracts/primitive_stream.kf
resolves: https://github.com/truflation/tsn-sdk/issues/32
> chore: sync primitive and composed's get index change

- core/contractsapi/stream.go
resolves: https://github.com/truflation/tsn-sdk/issues/29 
I tested it on `tsna-data-provider` by trying `task migrations-diff-rolling`
> fix: return correct error on NewStream method 

- core/contracts/composed_stream_template.kf
- core/contracts/primitive_stream.kf
resolves: https://github.com/truflation/tsn-data-provider/issues/225
> fix: cast null to correct return structure

- core/contracts/composed_stream_template.kf
- core/contracts/primitive_stream.kf
- core/contractsapi/stream_procedures.go
- core/types/stream.go
> feat: fetch values from given base date

- core/contracts/composed_stream_template.kf
- core/contracts/primitive_stream.kf
- tests/integration/composed_stream_test.go
- tests/integration/permission_test.go
- tests/integration/primitive_stream_test.go
resolves: https://github.com/truflation/tsn/issues/633
> feat: more precision number on contract

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/semantic-pr.yml
- core/contracts/composed_stream_template.kf
- core/contracts/primitive_stream.kf
- core/contractsapi/stream.go
- core/contractsapi/stream_procedures.go
- core/types/stream.go
- tests/integration/composed_stream_test.go
- tests/integration/primitive_stream_test.go
resolves: https://github.com/truflation/tsn-sdk/issues/43
- I also add some `.github` files
- test with `go test ./...` all green
> feat: get first record

- core/contracts/composed_stream_template.kf
- core/contractsapi/composed_stream.go
- core/types/composed_stream.go
- tests/integration/composed_stream_test.go
- tests/integration/permission_test.go
- tests/integration/util.go
- added start date
resolves: https://github.com/truflation/tsn/issues/664
Checked with tsn-data-provider it has taxonomy_id and start_date now
> feat: set taxonomy with start date

- core/contracts/primitive_stream.kf
- core/contractsapi/composed_stream.go
I got a problem where it fails to fetch base value. look like a default value is needed in if both > and <= used
related: https://github.com/truflation/tsn-sdk/pull/46
resolves: https://github.com/truflation/tsn/issues/672
go test ./... now green and works
> chore: add fallback for  to ensure valid date in queries

- core/logging/logging.go
- core/tsnclient/deploy_composed_streams_with_taxonomy.go
- core/tsnclient/get_all_streams.go
resolves: https://github.com/truflation/tsn-sdk/issues/53
the logs will be look like this
I think the rest can be done in tsn-utils repository where if err => log something
> chore: use structured logs

- core/contractsapi/abstract_api.go
- core/contractsapi/composed_stream.go
- core/contractsapi/decode_call_results.go
- core/contractsapi/deploy_stream.go
- core/contractsapi/destroy_stream.go
- core/contractsapi/primitive_stream.go
- core/contractsapi/stream.go
- core/contractsapi/stream_procedures.go
- core/tsnclient/client.go
- core/tsnclient/deploy_composed_streams_with_taxonomy.go
- core/tsnclient/get_all_streams.go
- core/types/composed_stream.go
- core/types/contract_values.go
- core/util/ethereum_address.go
- core/util/stream_id.go
- core/util/visibility_enum.go
resolves: https://github.com/truflation/tsn-sdk/issues/55
> chore: display detailed message on error

- core/contracts/composed_stream_template_unix.kf
- core/contracts/contract_contents.go
- core/contracts/primitive_stream_unix.kf
- core/contractsapi/composed_stream.go
- core/contractsapi/deploy_stream.go
- core/contractsapi/primitive_stream.go
- core/contractsapi/stream_procedures.go
- core/types/composed_stream.go
- core/types/contract_values.go
- core/types/primitive_stream.go
- core/types/stream.go
- tests/integration/composed_stream_unix_test.go
- tests/integration/primitive_stream_unix_test.go
- tests/integration/util.go
resolves: https://github.com/trufnetwork/sdk-go/issues/62
Tested with unit test, both previous and new test are green
> feat: contract support timestamp

- core/contractsapi/primitive_stream.go
- core/contractsapi/stream_procedures.go
- core/types/primitive_stream.go
- core/types/stream.go
- correct type for data values
- custom procedure execution for downstream usage (SDK py)
- fix #65 
already implemented downstream
> feat: custom procedure and call from 

- README.md
This pull request includes an update to the `README.md` file to provide more detailed information on how to create stream locators. The changes clarify the options available for stream locator creation and include additional comments to guide users on when to use each option.
Enhancements to documentation:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L51-R67): Added detailed comments explaining the two options for stream locator creation: using the data provider's address and using the current provider's address. This helps users understand when to use each option and provides example code for both scenarios.
resolves: https://github.com/trufnetwork/sdk-go/issues/83
> docs: info about stream locator

- core/contractsapi/primitive_stream.go
- core/contractsapi/stream_procedures.go
- core/tnclient/client.go
- core/tnclient/deploy_composed_streams_with_taxonomy.go
- core/types/primitive_stream.go
- core/types/stream.go
- core/types/tsn_client.go
- tests/integration/batch_operations_test.go
- tests/integration/composed_actions_test.go
- tests/integration/deploy_composed_streams_with_taxonomy_test.go
- tests/integration/util.go
review after: https://github.com/trufnetwork/sdk-go/pull/104
This pull request includes several changes to `core` and `tests` files, focusing on refactoring and re-enabling previously commented-out code. The most important changes include re-enabling the `InsertRecords` method, updating the `GetIndex` method, and modifying the `DeployComposedStreamWithTaxonomy` function.
* [`core/contractsapi/primitive_stream.go`](diffhunk://#diff-5c5ecc9113d7e66ab9170adaa9c3acac541496a2ae26804b16c86a66aa31e254L83-R109): Re-enabled and refactored the `InsertRecords` method to handle multiple input records and perform necessary data transformations.
* [`core/contractsapi/stream_procedures.go`](diffhunk://#diff-148344d9988d98b755aac9ec6d8a94198b8c92d93ca3afc6d82ffcd504cbc978L199-R245): Re-enabled and …
> feat: get index value from a stream

- .env.example
- .gitignore
- core/contractsapi/batch_deploy_streams.go
- core/contractsapi/composed_stream.go
- core/contractsapi/decode_call_results.go
- core/contractsapi/stream.go
- core/contractsapi/stream_procedures.go
- core/tnclient/client.go
- core/types/stream.go
- core/types/stream_types.go
- core/types/tsn_client.go
- core/util/ethereum_address.go
- go.mod
- go.sum
- tests/integration/batch_operations_test.go
- tests/integration/batch_stream_creation_test.go
- tests/integration/composed_actions_test.go
- tests/integration/deploy_composed_streams_with_taxonomy_test.go
- tests/integration/list_streams_test.go
- tests/integration/permission_test.go
- tests/integration/primitive_actions_test.go
- tests/integration/server_fixture.go
- tests/integration/util.go
This PR enhances the SDK by improving data handling, operational efficiency for stream deployments, and local testability:
*   **Core Data Handling (`decode_call_results.go`):**
*   Introduced a significantly more robust and flexible `DecodeCallResult` function. This generic utility simplifies decoding of smart contract call results into various Go types (structs with `json` tag mapping, scalars), reducing boilerplate and potential runtime errors for developers.
*   Fixes previous issues where decoding could fail for non-standard SQL types, such as boolean values.
*   **Batch Stream Deployment (`batch_deploy_streams.go`):**
*   Added `BatchDeployStreams` functionality, enabling the deployment of multiple data streams in a single transaction. This improves efficiency and reduces network …
> feat: add batch deployment and existence checking for streams

- README.md
- docs/api-reference/client.md
resolves: https://github.com/trufnetwork/node/issues/934
> docs: update README with mainnet examples

- README.md
- examples/main.go
resolves: https://github.com/trufnetwork/node/issues/967
> fix: correct wrong command and delete wrong function from README

- core/contractsapi/role_management.go
- core/tnclient/client.go
- core/types/role_types.go
- core/types/tsn_client.go
- docs/stream-permissions.md
resolves: https://github.com/trufnetwork/sdk-go/issues/124
resolves: https://github.com/trufnetwork/sdk-go/issues/125
Revoke
It got deleted from DBs
> feat: manage which wallet can write on network

- core/contractsapi/stream_procedures.go
- core/contractsapi/stream_procedures_test.go
- Replaced repetitive log parsing code with a new `parseLogsForMetadata` function to enhance code readability and maintainability.
- Improved error handling for log format validation within the new parsing function
- fix #150
> chore: parse logs correctly
