trufnetwork/sdk-go

- README.md
Added a link to the "default TSN contracts" guide in the "type of streams" section for more comprehensive information, ensuring users can easily find and understand the relevant contracts.
> fix: improve documentation

- core/tsnclient/client.go
assigned kwilClient.Signer into c.Singer to properly pass the validation.
Alternatively, remove `Signer` since it is already in kwilClient anyway.
resolves: https://github.com/truflation/tsn-sdk/issues/9
> build: assign kwilClient.Signer to Client.Signer

- README.md
Corrected the URL for the staging network in the README file.
> chore(docs): update staging network URL in README.md

- core/contractsapi/composed_stream.go
- core/contractsapi/deploy_stream.go
- core/contractsapi/primitive_stream.go
- core/contractsapi/stream.go
- core/tsnclient/client.go
resolves: https://github.com/truflation/tsn-sdk/issues/35
I separated `NewStream` into `NewStream` and `LoadStream`
The difference is, that `NewStream` just like its name, creates something new, while `LoadStream` needs to load something that exists (that's why we need to check it)
> fix: able to deploy stream without getting error

- core/contracts/composed_stream_template.kf
I will sync tsn and tsn-data-provider after this one merged.
```
kwil-cli database call -a=get_record date_from:2024-09-01 date_to:2024-09-09 -n=st1b148397e2ea36889efad820e2315d
| date_value |  value   |
+------------+----------+
| 2024-09-01 | 8527.336 |
| 2024-09-02 | 8490.750 |
```
```
kwil-cli database call -a=get_record date_from:2024-08-31 date_to:2024-09-09 -n=st1b148397e2ea36889efad820e2315d
| date_value |  value   |
+------------+----------+
| 2024-08-30 | 8527.194 |
| 2024-09-01 | 8527.336 |
```
```
kwil-cli database call -a=get_record date_from:2024-08-30 date_to:2024-09-09 -n=st1b148397e2ea36889efad820e2315d
| date_value |  value   |
+------------+----------+
| 2024-08-30 | 8527.194 |
| 2024-09-01 | 8527.336 |
```
everything is in correct ways
> fix: unnecessary set of date and value on the optimized contract

- core/contracts/composed_stream_template.kf
- core/contracts/primitive_stream.kf
also changed `get_index_change` parameters order to ensure consistency with other procedures (`get_index` and `get_record`)
> fix: remove duplicates from `get_record` responses

- core/contracts/primitive_stream.kf
I am matching the methodology here
```
Base Value: This is selected by first looking for a data point for 2010-01-01. If there is no
value on that date, the system will find the first value before that date (for example
2009-12-28) and set the index value for 2010-01-01 at 100.0. If there is no data for
2010-01-01, the system will select the closest available value after this date for this data
point. This will raise a red flag in the system and the data will undergo the usual process
for when a new data provider is added.
```
resolves: https://github.com/truflation/tsn/issues/672
> fix: incorrect base value fetched after base date

- core/tsnclient/deploy_composed_streams_with_taxonomy.go
- core/types/tsn_client.go
- tests/integration/deploy_composed_streams_with_taxonomy_test.go
- add a utility function to allow tsn-sdk users to deploy a composed contract with taxonomy in one go.
resolves: https://github.com/truflation/tsn/issues/692
go test the newly integration test
> feat: create composed stream with taxonomy included

- core/contractsapi/primitive_stream.go
- core/types/primitive_stream.go
- tests/integration/get_all_streams_test.go
- New type was based on a previous version where integer was used, leaving out decimals. This PR addresses this correctly
- fix #67 
tests passed
> feat: update Value field type to float64 in InsertRecordUnixInput

- tests/integration/batch_operations_test.go
- benchmark our insert capabilities. however note that this is a unreal baseline where the node is on the same machine as the inserter
- fix #70 
run tests
```
go test -v ./tests/integration -run TestBatchOperations -count=1
=== RUN   TestBatchOperations
=== RUN   TestBatchOperations/TestSequentialSmallBatches
[Small Batches] All insertions completed in 4.350266812s (avg 8.700533ms per batch, 1.740106ms per record)
[Small Batches] All transactions confirmed in 9.165253162s
=== RUN   TestBatchOperations/TestSequentialLargeBatches
[Large Batches] All insertions completed in 5.315716126s (avg 10.631432ms per batch, 106.314µs per record)
[Large Batches] All transactions confirmed in 2m1.424877338s
=== RUN   TestBatchOperations/TestRapidSingleRecordInserts
[Single Records] All insertions …
```
> feat(tests): integration tests for rapid insertions

- core/contractsapi/primitive_stream.go
- core/types/primitive_stream.go
- Updated InsertRecords and InsertRecordsUnix methods to accept optional transaction options (opts ...client.TxOpt).
- Modified checkedExecute method to handle the new options parameter, improving flexibility in transaction execution.
- Added necessary imports for client types in both core/contractsapi and core/types packages.
- fix #72 
not a breaking change
> feat: support transaction options (primitive)

- core/contracts/contract_contents.go
- core/contracts/helper_stream.kf
- core/contractsapi/deploy_stream.go
- core/contractsapi/helper_stream.go
- core/tnclient/client.go
- core/types/contract_values.go
- core/types/helper_stream.go
- core/types/tsn_client.go
- core/util/structAsArgs.go
- tests/integration/helper_stream_test.go
This pull request introduces a new helper stream type to the TN SDK, including its implementation, integration, and testing. The changes primarily focus on adding the helper stream functionality, updating the client interface, and providing necessary utilities and tests.
Key changes include:
* [`core/contracts/contract_contents.go`](diffhunk://#diff-e58a3104aca531183b4c8c09e849b9d885594f294cf1f6d04079097848e884b2R16-R18): Added `HelperContractContent` to embed the helper stream contract.
* [`core/contracts/helper_stream.kf`](diffhunk://#diff-15d712478adb7d8f76e8b78102fa8db58020afe7c19249a340ac83792df63434R1-R48): Introduced the helper stream contract with procedures for inserting records and getting database IDs.
* [`core/contractsapi/helper_stream.go`](diffhunk://#diff-40a98e931d8469e6e5a …
> feat: insert large data into multiple streams

- core/contractsapi/primitive_stream.go
- core/contractsapi/stream_procedures.go
- core/types/primitive_stream.go
- core/types/stream.go
- tests/integration/primitive_stream_unix_test.go
- Add `GetFirstRecordUnix` type and method to support Unix timestamp-based first record retrieval
- Change empty record handling to return `nil` instead of error for better UX
- Add comprehensive test coverage for empty stream scenarios
resolves: #78 
Added new test cases in `primitive_stream_unix_test.go`:
- `EmptyStreamOperations`: verifies correct behavior when stream has no records
- Tests empty stream without parameters
- Tests empty stream with afterDate parameter
- Extended existing `DeploymentWriteAndReadOperations` test to verify non-empty stream behavior
- All tests pass successfully
> feat: receive first value from the timestamp stream

- core/util/stream_id.go
This pull request introduces a new function to the `core/util/stream_id.go` file to allow the creation of a `StreamId` without validation. 
Key change:
* Added `NewRawStreamId` function to create a `StreamId` directly from a string without performing validation.
resolves: https://github.com/trufnetwork/adapters/issues/102
> feat: get stream id without validation or modification

- core/contracts/composed_stream_template.kf
- core/contracts/composed_stream_template_unix.kf
- core/contractsapi/composed_stream.go
- core/types/composed_stream.go
- tests/integration/composed_stream_test.go
- tests/integration/composed_stream_unix_test.go
This pull request introduces changes to the `core/contracts/composed_stream_template.kf`, `core/contracts/composed_stream_template_unix.kf`, `core/contractsapi/composed_stream.go`, `core/types/composed_stream.go`, and related test files to add support for an `end_date` field in taxonomies. The changes ensure that taxonomies have both start and end dates, allowing for more precise control over their validity periods.
* Added `end_date` field to the `taxonomies` table and updated relevant procedures to handle this new field in `core/contracts/composed_stream_template.kf` and `core/contracts/composed_stream_template_unix.kf`. [[1]](diffhunk://#diff-54db118729c74004bc005f49f1b3b760833945b7954bdcf56626de3fa8d10a2dL15-R16) [[2]](diffhunk://#diff-54db118729c74004bc005f49f1b3b760833945b7954bdcf566 …
> feat: set taxonomy with end date

- core/contracts/helper_stream.kf
- core/contractsapi/helper_stream.go
- core/types/helper_stream.go
- tests/integration/helper_stream_test.go
- tests/integration/server_fixture.go
- tests/integration/util.go
- Added new `filter_initialized` procedure to the helper contract to filter out non-initialized streams
- Implemented corresponding Go API in the SDK to support this functionality
- Added comprehensive test coverage for the new feature
- Created a reusable server fixture for integration tests
- related to https://github.com/trufnetwork/adapters/issues/141
- Added integration tests that verify the functionality works correctly
- Tests cover both successful filtering of initialized streams and handling of error cases
- Created a reusable server fixture to simplify future integration testing
> feat: add filter_initialized procedure to helper stream contract

- core/contractsapi/deploy_stream.go
- core/contractsapi/destroy_stream.go
- core/tnclient/client.go
- core/types/tsn_client.go
- tests/integration/get_all_streams_test.go
This pull request includes several changes aimed at improving the `DestroyStream` functionality in the codebase. The most important changes involve refactoring the `DestroyStream` method, updating the `DestroyStreamInput` struct, and cleaning up related test cases.
Refactoring and updates to `DestroyStream` functionality:
* [`core/contractsapi/destroy_stream.go`](diffhunk://#diff-0c1c168438ae712efb878adb3dcd245bf194c5f534381ee65d891c959ec37c6dR4-R24): Refactored the `DestroyStream` function to use the `Execute` method for stream deletion and updated the `DestroyStreamInput` struct to include `context` and `auth` imports. Removed the `Validate` method and the `DestroyStreamOutput` struct.
* [`core/tnclient/client.go`](diffhunk://#diff-9389eb75723e26b70059b839c5b6cafce5f48c3201dc47d12f868e68 …
> feat: delete a stream

- core/contractsapi/composed_stream.go
- core/types/composed_stream.go
- tests/integration/composed_actions_test.go
This pull request includes significant updates to the `DescribeTaxonomies` functionality in the `core/contractsapi/composed_stream.go` file, along with changes to the `Taxonomy` and `TaxonomyItem` structs and integration tests. The changes aim to enhance the data structure and improve the overall functionality of the `DescribeTaxonomies` method.
* [`core/contractsapi/composed_stream.go`](diffhunk://#diff-ed1ac9bc894ab61c93e23dbad352c2b40d821a13cb53f2adb4f0681cacddd9d0L68-R89): Updated the `DescribeTaxonomies` method to include new parameters and handle additional fields such as `DataProvider`, `StreamId`, `CreatedAt`, and `GroupSequence`. This also involved updating the call to `DecodeCallResult` and modifying the logic to parse and convert these fields. …
> feat: describe taxonomy

- core/contractsapi/abstract_api.go
- core/contractsapi/stream.go
- core/contractsapi/stream_procedures.go
- core/types/contract_values.go
- core/types/stream.go
- tests/integration/permission_test.go
- tests/integration/util.go
This pull request includes several changes to the `contractsapi` package, primarily focused on updating methods and types for handling metadata and stream operations. The most important changes include modifying the `Action` struct methods to use new input types, updating metadata handling, and correcting type references.
* Modified `AllowReadWallet` and `DisableReadWallet` methods to use `ReadWalletInput` instead of individual parameters.
* Added `AllowComposeStream` and `DisableComposeStream` methods using `StreamLocator` and `DisableMetadataByRefInput` respectively.
* Updated `SetComposeVisibility` and `SetReadVisibility` methods to use `VisibilityInput`. [[1]](diffhunk://#diff-d9ce8244956d3e24308ccfea44fa264047d352cec5fe2046b1a64ff643606518L60-R80) …
> feat: set metadata for a stream

- core/contractsapi/stream_procedures.go
- core/types/stream.go
- tests/integration/primitive_actions_test.go
This pull request includes significant updates to the stream procedures and related tests in the `core` module. The changes primarily focus on refactoring the `GetFirstRecord` functionality, updating its input structure, and enhancing the integration tests to reflect these updates.
Refactoring and functionality updates:
* [`core/contractsapi/stream_procedures.go`](diffhunk://#diff-148344d9988d98b755aac9ec6d8a94198b8c92d93ca3afc6d82ffcd504cbc978L230-R272): Refactored the `GetFirstRecord` method to use a new input structure and updated its logic for handling optional arguments and parsing results.
Input structure updates:
* [`core/types/stream.go`](diffhunk://#diff-43cbe295ede7ffece0864e9e613a8808c8cc3424632dd1b23f665162599aa153L25-R26): Removed the `GetFirstRecordUnixInput` type and …
> feat: get first record from a stream

- core/contractsapi/batch_deploy_streams.go
- core/contractsapi/deploy_stream.go
- core/contractsapi/destroy_stream.go
- core/contractsapi/stream.go
- core/tnclient/client.go
- core/types/tsn_client.go
- examples/main.go
log: this need to be configure on AWS
```
panic: authenticate error: domain mismatch: configured 'https://gateway.infra.truf.network' != remote https://infra.truf.network
goroutine 1 [running]:
main.main()
/home/micbun/trufnetwork/sdk-go/examples/main.go:28 +0x20f
exit status 2
```
related: https://github.com/trufnetwork/node/pull/930
resolves: https://github.com/trufnetwork/sdk-go/issues/114
> chore: replace standard client with gatewayClient

- README.md
contract naming and hashing is about architecture v1
> docs: remove outdated concept
